FilOzone/pdp

- .github/ci.yml
> Try adding github actions CI

- contracts/src/PDPService.sol
- contracts/test/PDPService.t.sol
> Proofset data, Create, Delete

- contracts/src/PDPService.sol
- contracts/test/PDPService.t.sol
This adds batching to the find operation by default to match the other state operations.
> Batch find

- tools/add.sh
- tools/createproofset.sh
- tools/deploy-devnet.sh
- tools/find.sh
- tools/remove.sh
- tools/size.sh
I've been using these scripts to do basic gas measurement and state inspection on a lotus devnet.  They seem useful enough to share.
> Devnet testing scripts

- contracts/src/PDPService.sol
- contracts/test/PDPService.t.sol
> Proofset ownership transfer

- contracts/src/PDPService.sol
- contracts/test/PDPService.t.sol
This closes out the suggested TODO following on in #38
Please let me know of any edge cases or getters I haven't checked
> Thorough testing of add and remove 

- contracts/src/PDPRecordKeeper.sol
- contracts/test/PDPRecordKeeper.t.sol
> Basic record keeper

- contracts/src/PDPService.sol
> Add events since EVM return values are hard to work with

- contracts/src/Cids.sol
- contracts/test/PDPService.t.sol
I found this commit lying around that I think I intended to squash into a prior PR.
> Minor cleanups in testing

- contracts/src/PDPVerifier.sol
- contracts/src/SimplePDPService.sol
- contracts/test/PDPVerifier.t.sol
- contracts/test/SimplePDPService.t.sol
- tools/deploy-calibnet.sh
- tools/deploy-devnet.sh
- PDPService -> PDPVerifier:The Verfier manages the proof set and verfies the submitted prove
- RecordKeeper -> SimplePDPService: SimplePDPService implementing features that backs up an application, i.e: SLA setting using proof records;
> Contract name refactor

- contracts/src/PDPVerifier.sol
- contracts/src/SimplePDPService.sol
- contracts/test/PDPVerifier.t.sol
- contracts/test/SimplePDPService.t.sol
> Change PDP listener interface to multiple methods rather than structured payload

- contracts/src/PDPVerifier.sol
- contracts/test/PDPVerifier.t.sol
Use the randomness precompile to generate challenges
Closes #44
> Secure challenge gen

- src/PDPVerifier.sol
- src/SimplePDPService.sol
- test/PDPVerifier.t.sol
- test/SimplePDPService.t.sol
Before this gets baked into everything.
> Fix spelling of possession

- src/SimplePDPService.sol
- test/SimplePDPService.t.sol
Replaces https://github.com/FilOzone/pdp/pull/84/files.
> fix: emit fault record event with more details

- src/IPDPProvingSchedule.sol
> Match iface to implementation

- src/PDPVerifier.sol
- tools/deploy-calibnet.sh
This isn't strictly necessary but it simplifies curio integration and is generically useful.
> ProofFee endpoint

- src/PDPVerifier.sol
- src/SimplePDPService.sol
- test/PDPVerifier.t.sol
- test/SimplePDPService.t.sol
Closes #79 .
Add more information to events and make them easy to consume.
> Fix PDP events UX

- README.md
- design.md
> feat(docs): add PDP design documentation

- src/PDPVerifier.sol
- test/PDPVerifier.t.sol
This turns these refunds into "tail calls" where we guarantee that we make no changes to state after processing the refund. This prevents any re-entrancy issues in _this_ contract.
In theory, this could trigger a re-entrancy issue in the calling contract, but that's not our problem (it's something we'll just need to document).
> fix: avoid refund re-entrancy issues by refunding at the bottom

- src/PDPVerifier.sol
- src/Proofs.sol
- test/Cids.t.sol
- test/PDPVerifier.t.sol
- test/SimplePDPService.t.sol
Tests in response to identified gap in audit.
> Audit test suggestions

- src/PDPVerifier.sol
> Cache loads in local vars

- .gitignore
- src/PDPVerifier.sol
in PDPVerifier.sol
add .zed into .gitignore
> Fix outdated comment and clean up whitespace

- README.md
- docs/design.md
Add dependency note and improve code block formatting in the documentation with syntax highlighting.
> Add note about Foundry build dependency and improve code format

- foundry.toml
- test/PDPVerifier.t.sol
While we are modifying the mainnet contract in response to issue resolved by #142 we'll also do proper compiler optimizations targeting expensive deploy and cheaper gas running
> compiler optimizations

- .gitignore
- tools/deploy-devnet.sh
> fix: devnet deployment script

- tools/claim-owner.sh
- tools/propose-owner.sh
Scripts for changing proofset ownership.  Need to test this out on network.
> scripts for ownership transfer

- README.md
Update deploy instructions in the Readme
> chore: update to correct deploy script in readme

- src/PDPVerifier.sol
- test/PDPVerifier.t.sol
> Fallback to unsafe oracle feed when safe call fails

- src/PDPVerifier.sol
- test/PDPVerifier.t.sol
> Safe migrate function scaffold
