Makefile, contracts/src/BitOps.sol, contracts/src/Proofs.sol, contracts/test/BitOps.t.sol, contracts/test/Proofs.t.sol
The proof verification is adapted from OpenZeppelin libraries, with the hash changed to SHA256. The testing code includes building of trees from an array of roots, which we must replicate off-chain.
=> Implemented Merkle proofs and verification

contracts/src/Proofs.sol, contracts/test/Proofs.t.sol
We need to verify the position of a leaf and a protocol-determined offset, not any provider-chosen leaf.
=> Change Merkle proof scheme to verify leaf position

contracts/src/Proofs.sol, contracts/test/Proofs.t.sol
This is only part of Filecoin piece CID compatibility, but should do the job for power-of-two data sizes.
=> Implement SHA254 hashing for the merkle tree

contracts/src/Cids.sol, contracts/src/PDPService.sol, contracts/test/PDPService.t.sol
This is a prefactor extracted from my work implementing `provePosession`. In addition to adding the challenge epoch, I realised there is insufficient testing for the basic logic around adding and removing pieces, and resolving all this was going to balloon the PR adding proving (for which the testing will be quite involved).
I haven't added all the necessary tests here, but it would be great @ZenGround0 if you could follow on from this and fill out those workflow tests.
=> Record next challenge epoch. Extract CID to library.

contracts/src/Cids.sol, contracts/src/PDPService.sol, contracts/src/Proofs.sol, contracts/test/Cids.t.sol, contracts/test/PDPService.t.sol, contracts/test/ProofUtil.sol, contracts/test/Proofs.t.sol
Implemented PDPService.provePosession method, with tests.
At present, uses the challenge epoch itself as the random seed rather than fetching chain randomness from that epoch (see #44).
I moved the Merkle tree and proof building code alongside the verification code since now its needed from multiple test files. The compiler should strip un-called functions from these libraries when deploying.
Closes #9. Closes #10.
=> Implement proof of possesion

contracts/src/Cids.sol, contracts/src/PDPRecordKeeper.sol, contracts/src/PDPService.sol, contracts/test/PDPService.t.sol, tools/README.md, tools/createproofset.sh, tools/deploy-devnet.sh
=> Integrate record keeper

contracts/src/PDPRecordKeeper.sol, contracts/src/PDPRecordKeeperApplication.sol, contracts/src/PDPService.sol, contracts/test/PDPRecordKeeper.t.sol, contracts/test/PDPService.t.sol
This is a light refactor as the outcome of exploring what PDP application conventions could look like.  This change cements the decision for applications to interact with PDP by getting called back with different operations.
Alternatively we could have had an interface with separate methods for notifying each operation but I didn't see a compelling enough case for this.
=> Rename record keeper as application

contracts/src/PDPRecordKeeper.sol, contracts/test/PDPRecordKeeper.t.sol
With a slight shift in perspective the record keeper is now the first instance of our default PDP application.  This PR augments our default application to tell users what proving period and challenge count should be.
@magik6k I think this is most of what you need to avoid configuration state outside of the chain.  This is flexible enough where it allows proving early which should make setting a proving offset a moot point.  Basically lets say you first add data at 2:30 AM which samples a challenge.  The next day you could prove at 2 PM and then you don't need to prove again until 2 PM.
=> Proving specification hints now given in the PDP application

contracts/src/SimplePDPService.sol, contracts/test/PDPVerifier.t.sol, contracts/test/SimplePDPService.t.sol
As part of requirements we want to allow on chain enforcement of challenge count during proving without baking assumptions directly in the pdp verifier.
So we want to put this in the simple pdp service.  To do this well wrt testing we want to refactor simple pdp service a bit.  This PR extracts record keeper functionality to a base contract that can be shared by simple pdp service and a testing contract that forgoes the complexity of simple pdp service.  
This PR also introduces functions on simple pdp service that make discovery of faults easy for off chain observers.
=> Enforce challenge count in simple pdp service

contracts/foundry.toml, tools/deploy-calibnet.sh, tools/deploy-devnet.sh, tools/testBurnFee.sh, tools/upgrade-contract-calibnet.sh
For whatever reason, when running solidity 0.8.20, we get a visibility error in the tests:
```
Error (9582): Member "FaultRecord" not found or not visible after argument-dependent lookup in type(contract SimplePDPService).
--> test/SimplePDPService.t.sol:188:14:
|
188 |         emit SimplePDPService.FaultRecord(SimplePDPService.FaultType.LATE, 3);
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Pin solc version in foundry.toml

src/PDPVerifier.sol, src/SimplePDPService.sol, test/PDPVerifier.t.sol, test/SimplePDPService.t.sol
Enforce the proof of possession challenge epoch to be within a 30 minute challenge window at the end of the proving period.  
The motivation is 
1) This forces 24 hour proof of access rather than a single period of access the duration of challengeFinality epochs every 48 hours fixing a problem pointed out by @irenegia and @lucaniz
2) Because 30 minutes is too restrictive for unsealing this adds a time guarantee that PDP SPs truly have an unsealed copy and are not unsealing for proofs fixing a problem pointed out by @magik6k 
To do this with the existing architecture this PR adds a parameter to the NextProvingPeriod method on the verifier allowing the user to pass in the challengeEpoch.  And it adds the parameter to the listener interface.  Now the PDPService can enforce its own …
=> Challenge window restriction

src/IPDPProvingSchedule.sol, src/PDPVerifier.sol
This makes it easier for curio or other SP tools to consume standard proving window meta data that is likely to be standard across listeners.  See integration into curio [here](https://github.com/filecoin-project/curio/pull/334)
=> Proving Schedule interface

src/IPDPProvingSchedule.sol, src/PDPVerifier.sol, src/SimplePDPService.sol, test/PDPVerifier.t.sol, test/SimplePDPService.t.sol
=> Remove special casing of first add

Makefile, tools/deploy-calibnet.sh
Either `forge` or lotus eth api recently updated to some sort of terrible behavior where nonce tracking no longer works so I implement this in the script itself.
=> Update makefile to use script compatible env var names

src/Fees.sol, test/Fees.t.sol
We were failing on estimation as base fee is set to 0
=> Allow fee safety checks to pass when gas estimating

src/PDPVerifier.sol
3.3
The audit notes that transfers have issues interacting with smart wallet / more sophisticated sending contracts. A large reason for this is that transfer puts a very restricted limit on gas usage in the transfer function. This is a blanket reentrency protection that we don't need. So this PR forwards full gas limit to the transfer to maximize sending contract compatibility.
=> Audit 3.3 Allow nontrivial gas for refund

src/PDPVerifier.sol
While debugging a nextProvingPeriod message I noticed that we emit  removals event in every message even if there are no removals.
=> Only process removals if there are any

README.md
=> chore: add link to security audit report in README

Makefile, src/PDPVerifier.sol, src/Proofs.sol, test/PDPVerifier.t.sol, test/Proofs.t.sol
As reported by @Kubuxu the contract does not currently check that inclusion proofs go down to the leaves.  So it is currently trivial to always get a valid proof by submitting the root as a leaf and an empty array of siblings as a proof. 
This PR fixes this by adding tree height into the inclusion proof verification library.
=> Actually check proof

src/PDPVerifier.sol, src/SimplePDPService.sol, src/interfaces/IPDPEvents.sol, src/interfaces/IPDPTypes.sol, src/interfaces/IPDPVerifier.sol, test/PDPVerifier.t.sol, test/SimplePDPService.t.sol
This PR refactors the PDP codebase to move all public-facing event and struct type definitions out of the implementation contracts and into dedicated interface files. This enables external contracts and tools to import only the necessary interfaces, reducing code size and improving modularity.
---
- **Created/updated interface files:**
- `src/interfaces/IPDPTypes.sol`: Contains all shared structs and enums (e.g., `RootData`, `Proof`, `RootIdAndOffset`).
- `src/interfaces/IPDPEvents.sol`: Contains all public-facing event declarations (e.g., `ProofSetCreated`, `RootsAdded`, `ContractUpgraded`, etc.).
- `src/interfaces/IPDPVerifier.sol`: Main interface for the PDPVerifier contract, importing types and events.
- **Refactored implementation contracts:**
- `PDPVerifier.sol` and …
=> Refactor PDP Events and Types into Interfaces for External Consumption

.github/workflows/add-issues-and-prs-to-fs-project-board.yml
Making clear that this file is manually copied now as a result of https://github.com/FilOzone/github-mgmt/pull/15
See https://github.com/FilOzone/github-mgmt/issues/10 for more info.
=> chore: update docs for add-issues-and-prs-to-fs-project-board.yml

src/IPDPProvingSchedule.sol
Reviewer @zenground0
I want FilecoinWarmStorageServiceStateView to implement IPDPProvingSchedule.
Most of these methods are actually view methods right now, mostly because these fields are in storage rather than being constants:
* `getMaxProvingPeriod`
* `challengeWindow`
I would prefer to change FilecoinWarmStorageService to make these constants, but it looks like they are intended to be configurable. Therefore these methods should be `view` instead of `pure`.
* Fix interface to actual view/pure in current FilecoinWarmStorageService
=> fix(IPDPProvingSchedule): Mark View Methods

src/IPDPProvingSchedule.sol, src/SimplePDPService.sol, test/SimplePDPService.t.sol
Ref: https://github.com/FilOzone/filecoin-services/issues/163
Ref: https://github.com/FilOzone/filecoin-services/pull/167
Aiming to reduce service contract size, but also wanting it to implement the necessary interface to be a listener for PDP, this bundles up all the configuration numbers into a single `getPDPConfig`, with the big dynamic one as `nextPDPChallengeWindowStart`. They now have the name in them too with the assumption that implementers of this may have other verifiers or interfaces to deal with so we can avoid conflicts.
Note though, `getPDPConfig` does have one slightly dynamic return, `initChallengeWindowStart` changes with `block.number` so each call to this will change per epoch.
=> feat!: switch to a more compact form of IPDPProvingSchedule

src/PDPVerifier.sol, src/interfaces/IPDPEvents.sol, test/PDPVerifier.t.sol, test/PDPVerifierProofTest.t.sol
Reviewer @zenground0
Curio is expecting `calculateProofFee` to be `view`.
What is preventing that is that we are logging that the timestamp is out of date before just using the data anyway.
That isn't a great way to handle the situation.
The prior behavior is equivalent to `getPriceUnsafe` but with an extra staticcall in the outdated case.
If we want to notice that the price is outdated we can monitor the oracle directly; this is no more difficult than watching for `PriceOracleFailure` logs.
On-chain logs shouldn't be used like `logger` logs.
A better way to think of them is like a SQL database row.
It's also probably not a great experience for the price to change and then your transaction reverts, but that's a separate issue.
* use `getPriceUnsafe`, remove log
* make `calculateProofFee` …
=> Pyth: accept old prices without emit log

tools/upgrade-contract-calibnet.sh, tools/upgrade-contract.sh
Default to dry-run mode with `upgrade-contract-calibnet.sh` script
=> fix: default to dry-run mode with upgrade-script

.github/workflows/publish-abis.yml
The `publish-abis.yml` workflow was failing after the publishing of v2.1.0 here: https://github.com/FilOzone/pdp/actions/runs/17792160390 because it tried to run `npm ci`, but PDP doesn't have a `package.json` file at the root level iiuc.
I removed the unnecessary `npm ci` step. The workflow now only runs `forge install` which is all that's needed for Foundry dependency management.
=> fix: remove npm ci from publish-abis workflow

CHANGELOG.md, README.md, src/PDPVerifier.sol
=> build: PDP 2.2.0 release 

src/PDPVerifier.sol, test/PDPVerifier.t.sol
Removed in https://github.com/FilOzone/pdp/pull/201 as per original request. This puts that function back in just to give us the option to create empty data sets if needed, and gives us a smoother transition path for our dependencies (mainly Curio).
---
I'm just putting this option on the table, it doesn't have to be committed to, but it will make life a bit easier.
Ultimately the goal is to not need or use this, but it's not terrible having the option to create empty data sets, it solves the desire to create empty "buckets" S3 style, as mentioned in the original issue https://github.com/FilOzone/filecoin-services/issues/171 (and also expressed separately by Hugo).
See:
* https://github.com/filecoin-project/curio/issues/678
* https://github.com/filecoin-project/curio/pull/687
* …
=> feat: restore createDataSet
